---
title: "Chimerascan Tool"
output:
  github_document:
    toc: true
    fig_width: 5
    fig_height: 5
    dev: jpeg
---

```{r include = FALSE}
require(tidyverse); require(rmarkdown); require(knitr); require(sevenbridges); 

options(max.print = "99"); opts_knit$set(width = 99)
opts_chunk$set(cache=FALSE, tidy=FALSE)

source("~/cgrRNA/scratch/cgc_auth.R")

```

# Description

### base command

```{sh base command, eval=FALSE}

tar -xvzf index.tar.gz && \
python /opt/chimerascan/chimerascan/chimerascan_run.py \
--bowtie-path /opt/bowtie-1.1.2  ./  \
reads1.fastq reads2.fastq  chimeras_out \
--processors 6

python /opt/chimerascan/chimerascan/chimerascan_run.py --quals illumina --library-type fr-firststrand ./ --filter-false-pos /sbgenomics/Projects/11eb1a82-1bf7-4df7-b8d3-dd53e1567bd5/_1_hg19_bodymap_false_positive_chimeras.txt --bowtie-path /opt/bowtie-1.1.2 /sbgenomics/Projects/11eb1a82-1bf7-4df7-b8d3-dd53e1567bd5/SC080539_AACAACCA_L00R1_001.fastq /sbgenomics/Projects/11eb1a82-1bf7-4df7-b8d3-dd53e1567bd5/SC080539_AACAACCA_L00R2_001.fastq chimeras_out --processors 8


```

## Container

The docker conatiner is

``` cgrlab/chimerascan:latest ```

https://hub.docker.com/r/cgrlab/chimerascan/


# Ports

## Inputs

```{r inputs}

inputs = list(
  
input(id = "reads", label = "reads", description = "paired end reads", type = "File..."),
  
input(id = "index", label = "index", description = "chimerascan index", type = "File...", stageInput = "link")

)

```

## Arguments

```{r arguments}
arguments = CCBList(
CommandLineBinding(position = 1, valueFrom = list('"./"')),
CommandLineBinding(position = 101, valueFrom = list('"&& ls -lR"'))
)
```

## Outputs

```{r output}

outputs = list(

output(id = "std_out", label = "std_out", 
description = "standard output", type = "File",
metadata = list(from_tool = "chimerascan_run"),
glob = '"std.out"')
  
)


```

# Tool Definition

```{r 5 create tool object}

tool <- Tool(
id = "chimerascan_run", 
label = "Chimerascan Run",
hints = requirements(docker(pull = "cgrlab/chimerascan:latest"), cpu(1), mem(1000)),

baseCommand = "python /opt/chimerascan/chimaeracan/chimera_scan_run.py",

stdout = "std.out",

inputs = inputs,
  
arguments = arguments,
  
outputs = outputs)

```

# cwl file

```{r eval=create_cwl=="yes"}
write(tool$toJSON(pretty = TRUE), "cwl.json")
```

# Push app to cloud platform

```{r eval=platform_push=="yes"}
project$app_add("chimerascan_run", tool)
```

